<a href="https://colab.research.google.com/github/aiyaarie/CSST101-Laboratory/blob/main/AI_DEBATE_ADVISER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Table 1. Debate Arguments

In [2]:
debate <- data.frame(
  ArgumentID = c("A001", "A002", "A003", "A004", "A005", "A006"),
  Position = c("For", "For", "For", "Against", "Against", "Against"),
  Topic = c("Learning", "Productivity", "AI Literacy", "Academic Integrity", "Dependency", "Assessment"),
  Claim = c("AI can provide students with immediete learning support.", "AI can help students complete routing academic tasks more efficiently.", "Allowing AI use can help students develop AI literacy.", "Undisclosed AI-generated work may create academic integrity concerns.", "Excessive AI use may reduce students's independent problem-solving practice.", "AI use may make it more difficult to determine whether submitted work reflects student learning.")

)

debate

  ArgumentID Position Topic
1 A001       For      Learning
2 A002       For      Productivity
3 A003       For      AI Literacy
4 A004       Against  Academic Integrity
5 A005       Against  Dependency
6 A006       Against  Assessment
  Claim
1 AI can provide students with immediete learning support.
2 AI can help students complete routing academic tasks more efficiently.
3 Allowing AI use can help students develop AI literacy.
4 Undisclosed AI-generated work may create academic integrity concerns.
5 Excessive AI use may reduce students's independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.

# Table 2. Evidence

In [3]:
evidence <- data.frame(
  EvidenceID = c("E001", "E002", "E003", "E004", "E005", "E006"),
  ArgumentID = c("A001", "A002", "A003", "A004", "A005", "A006"),
  EvidenceType = c("Research", "Research", "Policy", "Policy", "Research", "Research"),
  Strength = c("Strong", "Moderate", "Strong", "Strong", "Moderate", "Strong")

)

evidence

  EvidenceID ArgumentID EvidenceType Strength
1 E001       A001       Research     Strong
2 E002       A002       Research     Moderate
3 E003       A003       Policy       Strong
4 E004       A004       Policy       Strong
5 E005       A005       Research     Moderate
6 E006       A006       Research     Strong

In [8]:
table(debate$Position)

Against     For
      3       3

In [9]:
nrow(debate)

[1] 6

# Connect Table of Debate and Evidence

In [11]:
knowledge_base <- merge(
  debate,
  evidence,
  by = "ArgumentID"
)

print(knowledge_base)

  ArgumentID Position              Topic
1       A001      For           Learning
2       A002      For       Productivity
3       A003      For        AI Literacy
4       A004  Against Academic Integrity
5       A005  Against         Dependency
6       A006  Against         Assessment
                                                                                             Claim
1                                         AI can provide students with immediete learning support.
2                           AI can help students complete routing academic tasks more efficiently.
3                                           Allowing AI use can help students develop AI literacy.
4                            Undisclosed AI-generated work may create academic integrity concerns.
5                     Excessive AI use may reduce students's independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.
  EvidenceID EvidenceType Strength
1       E001     Research   Strong
2       E002     Research Moderate
3       E003       Policy   Strong
4       E004       Policy   Strong
5       E005     Research Moderate
6       E006     Research   Strong

# Convert Evidence Strength into a Score

In [17]:
get_score <- function(Strength)(

  if(Strength == "Strong"){
    return(3)
  } else if (Strength == "Moderate"){
    return(2)
  } else if (Strength == "Weak"){
    return(1)
  } else {
    return(0)
  }
)

get_score("Moderate")

[1] 2

# Add Evidence Scores

In [18]:
knowledge_base$EvidenceScore <- sapply(
  knowledge_base$Strength,
  get_score
)

print(knowledge_base)

  ArgumentID Position              Topic
1       A001      For           Learning
2       A002      For       Productivity
3       A003      For        AI Literacy
4       A004  Against Academic Integrity
5       A005  Against         Dependency
6       A006  Against         Assessment
                                                                                             Claim
1                                         AI can provide students with immediete learning support.
2                           AI can help students complete routing academic tasks more efficiently.
3                                           Allowing AI use can help students develop AI literacy.
4                            Undisclosed AI-generated work may create academic integrity concerns.
5                     Excessive AI use may reduce students's independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.
  EvidenceID EvidenceType Strength EvidenceScore
1       E001     Research   Strong             3
2       E002     Research Moderate             2
3       E003       Policy   Strong             3
4       E004       Policy   Strong             3
5       E005     Research Moderate             2
6       E006     Research   Strong             3

# Convert Evidence Score to Support

In [19]:
classify_support <- function(score){

   if(score == 3){
    return("Strongly Supported")
  } else if (score == 2){
    return("Moderately Supported")
  } else if (score == 1){
    return("Weakly Supported")
  } else {
    return("No Support")
  }
}

classify_support(3)

[1] "Strongly Supported"

# Add Evidence Support

In [21]:
knowledge_base$EvidenceSupport <- sapply(
  knowledge_base$EvidenceScore,
  classify_support
)

print(knowledge_base)

  ArgumentID Position              Topic
1       A001      For           Learning
2       A002      For       Productivity
3       A003      For        AI Literacy
4       A004  Against Academic Integrity
5       A005  Against         Dependency
6       A006  Against         Assessment
                                                                                             Claim
1                                         AI can provide students with immediete learning support.
2                           AI can help students complete routing academic tasks more efficiently.
3                                           Allowing AI use can help students develop AI literacy.
4                            Undisclosed AI-generated work may create academic integrity concerns.
5                     Excessive AI use may reduce students's independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.
  EvidenceID EvidenceType Strength EvidenceScore      EvidenceSupport
1       E001     Research   Strong             3   Strongly Supported
2       E002     Research Moderate             2 Moderately Supported
3       E003       Policy   Strong             3   Strongly Supported
4       E004       Policy   Strong             3   Strongly Supported
5       E005     Research Moderate             2 Moderately Supported
6       E006     Research   Strong             3   Strongly Supported

# Search by Topic

In [23]:
search_topic <- function(topic) {

  result <- subset(
    knowledge_base,
    Topic == topic
  )

  if(nrow(result) == 0){
    cat("Topic not found")
  } else{
    print(result)
  }
}

search_topic("Learning")

  ArgumentID Position    Topic
1       A001      For Learning
                                                     Claim EvidenceID
1 AI can provide students with immediete learning support.       E001
  EvidenceType Strength EvidenceScore    EvidenceSupport
1     Research   Strong             3 Strongly Supported